### ISSUE TITLE
Add a few words describing basic behavior of inbuilt id stores?

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-spec#52]
Or is javadoc sufficient?

**Comment by arjantijms** [comment]
Javadoc counts as real spec, so if time is an issue this would certainly not be *needed*. In the JSF spec we have quite large sections of quite intricate and subtle behaviour that's only available in the Javadoc.

Ed Burns is very experienced with the EE specs (I think JSF was the first to be an open / JCP spec), so that surely must be okay.

**Comment by wmhopkins** [comment]
Fixed by #58 . Added a few words (not many) and a reference to the javadoc.
